# Generated by Django 5.2.5 on 2025-08-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='developer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='platforms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
