# Generated by Django 5.2.5 on 2025-08-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_developer_post_platforms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='post',
            name='platforms',
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
