# Generated by Django 5.2.5 on 2025-08-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_post_developer_remove_post_platforms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover_url',
            field=models.CharField(default='images/covers/silksong.jpg', max_length=255),
        ),
    ]
