# Generated by Django 5.2.5 on 2025-08-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_game_cover_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_url',
            field=models.CharField(default='images/covers/fable.jpg', max_length=255),
        ),
    ]
