# Generated by Django 5.2.5 on 2025-08-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_game_cover_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='cover_url',
        ),
    ]
